#!/bin/bash

cd $(dirname $0)
#请务必在下面填上自己的账号和密码
#用户名:
username=057181298992@DZKD.XY
#密码:
password=playboy0725

#下面内容不要修改
count=0
maxcount=10  #拨号失败重试次数
echo $username > Netkeeper.dat
poff -a > /dev/null
until test -n "`ifconfig | grep ppp`"
do
	if [ "$count" != 0 ]
		then echo "第$count次登录失败"
	fi
	realusername=`./dialnetkeeper`
	realusername=${realusername//\"/\\\"}
	cp PPPOE.conf temp
	echo "user \"$realusername\"" >> temp
	echo "password \"$password\"" >> temp
	mv temp /etc/ppp/peers/dsl-provider
	pon dsl-provider > /dev/null
	count=`expr $count + 1`
	if [ "$count" -eq "$maxcount" ]
	then echo 达到最大失败次数，请检查账户密码信息，或者稍后再试
	exit 0
	fi
	sleep 1
done
echo `plog | grep local`
echo 登录成功
rm Netkeeper.dat
exit 0
